### ISSUE TITLE
Patch fails if release has a comment in templates

### ISSUE THREAD

**Issue by fedterzi** [hickeyma/helm-mapkubeapis#20]
helm-mapkubeapis failed to patch a release because in its manifest it had a comment between `apiVersion` and `kind`:
```
...
apiVersion: extensions/v1beta1 # Daemonset is still not part of v1 api version\nkind: DaemonSet
...
```

Still a speculation, not 100% sure that it was the comment but this release was the only one that wasn't mapped (out of hundreds we had).

**Comment by hickeyma** [comment]
Its hard to tell exactly what's failing without seeing the manifest. Are you saying it doesn't find it or doesn't map it correctly?

Just wondering if this should be the string:
`apiVersion: extensions/v1beta1\n# Daemonset is still not part of v1 api version\nkind: DaemonSet`

**Comment by fedterzi** [comment]
Sorry I wasn't clear enough, this is from the output of `helm status release_name -o json` in the `manifest` key.

I'm saying that it doesn't find it correctly.

**Comment by hickeyma** [comment]
Would you be able to show thew template for this DaemonSet?

**Comment by fedterzi** [comment]
I can share part of it, relevant lines would be:
```
apiVersion: extensions/v1beta1 # Daemonset is still not part of v1 api version
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
```
