### ISSUE TITLE
"no deprecated or removed APIs" even thought there are some (Mapfile used)

### ISSUE THREAD

**Issue by c4tz** [hickeyma/helm-mapkubeapis#40]
Hey there,

I currently have a problem with this otherwise great plugin: I have a v2 Helm release on a cluster recently upgraded to k8s 1.17. `helm upgrade` fails with the known `unable to recognize [...]` error. I deleted all failed releases and am now in a state where I have a `DEPLOYED` helm as the latest, which has several removed/deprecated `apiVersion` entries in it. When I run `mapkubeapis` on this release, it tells me `Release 'myrelease' has no deprecated or removed APIs.`. But when I run `kubectl get configmap -n mynamespace myrelease.v2 -o=jsonpath='{.data.release}' | base64 -d | gzip -d | grep v1beta1` against it, it results in the following output (note the whitespace):

```yaml
apiVersion: extensions/v1beta1
apiVersion: apps/v1beta1
  apiVersion: extensions/v1beta1
```
I figured the corresponding resources were (shortened for readability):

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
[...]
apiVersion: apps/v1beta1
kind: StatefulSet
[...]
deployment:
  apiVersion: extensions/v1beta1
  kind: Deployment
```
So I thought (after reading #11 ) it may be caused by something regarding whitespace and line endings. I tried to duplicate the mappings like so:

```yaml
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\n  kind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
```
in order to eliminate the third case and also created duplicate mappings with `\r\n` in them to get rid of the other two. In the end, I had created 6 versions of each mapping (720 lines in total), but unfortunately, it didn't help and `mapkubeapis` still said it didn't find any deprecated/removed apiVersions.

This leads me to the following two questions:
* What am I doing wrong / Why doesn't it detect them?
* Would it be possible to implement reqex replacement (instead of plain strings) so that we can avoid duplicate entries in the mappings file?

**Comment by hickeyma** [comment]
@c4tz Sorry to hear you are having issues with a particular release. 

First off, without knowing the release format I am unable to know what the filter of the API needs to be. This is something you will need to troubleshoot further yourself unfortunately. 

Here are some suggestions or tips:

- Check against what is in the release and also the chart which was used to deploy the release.
- Avoid creating duplicates and making the mapping file very large. I would leave the mapping file as is if it works for most of the releases that you are mapping. 
- Create a new mapping file to help troubleshoot this issue. You can use the following flag to point to a new file: 

`--mapfile string           path to the API mapping file (default "config/Map.yaml")`

Let me know if you find out more.

**Comment by c4tz** [comment]
Hey @hickeyma,

thank you for the response. I was able to solve my problem in the meantime by manually editing the release and deleting several previous releases with "DEPLOYED" state that were floating around.

Nevertheless my second question (about the regex) remains untouched. Do you think it would impact performance much?

**Comment by hickeyma** [comment]
@c4tz I am not sure where the advantage would be as in nearly all cases a user would just have one entry per API.

**Comment by c4tz** [comment]
I was under the impression that if a release has indented occurrences of a deprecated API, the string-replace wouldn't catch those, because (as per my given example) the whitespace would prevent it to match the search string. Please tell me if I'm wrong here.

So if the relelase looks like this:

```yaml
deployment:
  apiVersion: extensions/v1beta1
  kind: Deployment
```
and the strings inside the mapping file look like this (default):

```yaml
deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Deployment"
```
there will be no match, because the whitespace before `kind` is not in the search string. Using a regex, we could avoid this behaviour.

**Comment by Nittarab** [comment]
Hi, I have the same problem:

```
$helm mapkubeapis --namespace kube-system --v2 parent --dry-run

2021/01/28 17:32:42 NOTE: This is in dry-run mode, the following actions will not be executed.
2021/01/28 17:32:42 Run without --dry-run to take the actions described below:
2021/01/28 17:32:42
2021/01/28 17:32:42 Release 'parent' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2021/01/28 17:32:42 Get release 'parent' latest version.
2021/01/28 17:32:43 Check release 'parent' for deprecated or removed APIs...
2021/01/28 17:32:43 Finished checking release 'parent' for deprecated or removed APIs.
2021/01/28 17:32:43 Release 'parent' has no deprecated or removed APIs.
2021/01/28 17:32:43 Map of release 'parent' deprecated or removed APIs to supported versions, completed successfully.
```
If I run:  `helm get manifest parent` 

```
[...]
# Source: shopmates/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parent-shopmates
  labels:
    app: parent-shopmates
    chart: "shopmates-3.3.7"
    release: parent
    heritage: Tiller
[...]
```

Kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.6000", GitCommit:"b02f5ea6726390a4b19d06fa9022981750af2bbc", GitTreeState:"clean", BuildDate:"2020-11-18T09:16:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
Helm Version:

```
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}

```

After reading this thread I tried to remove the old release:
```
$ helm history parent
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable"
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
12              Tue Jun 30 19:58:39 2020        DEPLOYED        shopmates-3.3.7 1.4.7           Upgrade complete
```
